version: "2"
linters:
  default: none
  enable:
    - gocritic
    - govet
    - ineffassign
    - nilerr
    - revive
    - staticcheck
    - unused
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  new: true
  fix: false
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
